# .codecov.yml — Coverage configuration for SyncGuard
# https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: yes
  notify:
    # Wait for all 5 coverage uploads before reporting:
    # 1 unit + 3 contracts (redis, postgres, firestore) + 1 e2e
    after_n_builds: 5

coverage:
  precision: 2
  round: down
  range: 70..100

  status:
    project:
      default:
        target: auto
        threshold: 2%
        base: auto
    patch:
      default:
        target: 77%
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "dist/"
  - "docs/"
  - "test/"
  - "**/*.test.ts"
  - "**/*.spec.ts"

flags:
  unit:
    paths:
      - "common/"
      - "redis/"
      - "postgres/"
      - "firestore/"
    carryforward: true
  contracts-redis:
    paths:
      - "common/"
      - "redis/"
    carryforward: true
  contracts-postgres:
    paths:
      - "common/"
      - "postgres/"
    carryforward: true
  contracts-firestore:
    paths:
      - "common/"
      - "firestore/"
    carryforward: true
  e2e:
    paths:
      - "common/"
      - "redis/"
      - "postgres/"
      - "firestore/"
    carryforward: true
